# Generated by Django 4.1.5 on 2023-02-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='selection_ad',
            new_name='items',
        ),
    ]
